### ISSUE TITLE
Only a folder with value of 0 is being uploaded.  File names do not appear.

### ISSUE THREAD

**Issue by Brian1111** [shamahoque/meanjs-s3-file-upload#1]
When I upload photos, the name of photos do not appear in S3 bucket.  Instead, inside the S3 bucket I see a folder called article with the value of 0.  Please see attached images of the S3 bucket 1 to 3.  No matter how many photos I upload, AWS S3 bucket shows the same thing.  As a result, when I upload a photo for an article, the photos of all the other articles also change.  MongoDB articles collection also shows 0 for all photo names as follows, please see attached image 4:   
"photo_url" : "https://imageblog.s3.amazonaws.com/article/0"

![s3_bucket_upload-1](https://cloud.githubusercontent.com/assets/12651236/17197912/ad710d0e-5425-11e6-864d-423a3ac2f3f6.png)
![s3_bucket_upload-2](https://cloud.githubusercontent.com/assets/12651236/17197913/ad719062-5425-11e6-80a4-38f4b42029a2.png)
![s3_bucket_upload-3](https://cloud.githubusercontent.com/assets/12651236/17197914/ad7b26b8-5425-11e6-8758-85e007764981.png)
![s3_bucket_upload-4](https://cloud.githubusercontent.com/assets/12651236/17197915/ad7ce82c-5425-11e6-9833-b2cfe0f8f787.png)

**Comment by Brian1111** [comment]
I found the solution.  In the file public/modules/core/services/fileupload.client.services.js, I added the following code just below line 9  `i += file.name; `   So it becomes like this:  
`// Upload files to S3
this.upload = function(file, i, folder, uploads, callback) {
     i += file.name;`

Now all the files and filenames appear in the S3 bucket in the folder article.   However, still a 0 appears before the name of the file, e.g., 0photo-10.jpg instead of photo-10.jpg.  Now I am trying to fix that also.

**Comment by shamahoque** [comment]
To keep the original filename in the S3 bucket folder, just need to change 'i' to 'file.name' in line 12 and line 23 of public/modules/core/services/fileupload.client.services.js

![screen shot 2016-07-29 at 1 37 06 am](https://cloud.githubusercontent.com/assets/1979272/17226818/2265bb20-552d-11e6-9fb2-0292ea2eaab9.png)

![screen shot 2016-07-29 at 1 37 17 am](https://cloud.githubusercontent.com/assets/1979272/17226829/33780c38-552d-11e6-98dc-a1ae186f6691.png)

I pushed a [fix](https://github.com/shamahoque/meanjs-s3-file-upload/commit/89987e35f61ad7221cc448d21b66da222887d1c2) for this behavior.

**Comment by Brian1111** [comment]
I tried it, now it is fixed.  The 0 does not appear before the file names.  I just installed grunt module to devDependencies so I can run it with nodemon.  Thanks.
